parameters:
  - name: dotnetVersion
    type: string
  - name: project
    type: string
  - name: packageId
    type: string
  - name: artifactName
    type: string

jobs:
- job: Pack
  displayName: 'dotnet pack $(artifactName)'
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '${{ parameters.dotnetVersion }}'
    - script: dotnet pack "${{ parameters.project }}" \
        --configuration Release \
        --no-build \
        --output "$(Build.ArtifactStagingDirectory)"
      displayName: 'dotnet pack'
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: '${{ parameters.artifactName }}'
