parameters:
  - name: dotnetVersion
    type: string
  - name: solution
    type: string
  - name: coverageDir
    type: string

jobs:
- job: Test
  displayName: 'Run tests & collect coverage'
  steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '${{ parameters.dotnetVersion }}'

    - script: |
        mkdir -p "${{ parameters.coverageDir }}"
        dotnet test "${{ parameters.solution }}" \
          --configuration Release \
          --no-build \
          --logger trx \
          --collect "XPlat Code Coverage" \
          --results-directory "${{ parameters.coverageDir }}"
      displayName: 'dotnet test + coverage'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Mango.Http Tests'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '${{ parameters.coverageDir }}/**/coverage.cobertura.xml'
        reportDirectory: '${{ parameters.coverageDir }}'